### ISSUE TITLE
Some questions :-)

### ISSUE THREAD

**Issue by pergolafabio** [tommyjlong/app_rtsp_sip#3]
Hey @tommyjlong 
I have succeeded now adding an RTSP stream to the call, leys say you have a SIP doorbell (6000) without any video capabilities
With dialplan below, when 6000 calls 666 (conference) ,  6001 , 6002 , 6003, ... are called too to join the conference
When 6001 or 6002 or 6003 picksup, those users will see the RTSP stream as video , because 6000 doesnt have video ... , and "doorbell" already joined the conference..

```
exten => 666,1,NoOp()
 same => n,Progress()
 same => n,Originate(Local/doorbell@default,exten,default,888,1,,aC(ulaw,alaw,h264)c(6000)n(Doorbell))
 same => n,Originate(PJSIP/6001,exten,default,777,1,,aC(ulaw,alaw,h264)c(6000)n(Doorbell)) 
 same => n,ConfBridge(1,myconferenceroom,default_user)
 same => n,Hangup()
 
exten => 777,1,NoOp()
 same => n,ConfBridge(1,myconferenceroom,admin_user)

exten => 888,1,NoOp()
 same => n,ConfBridge(1,myconferenceroom,default_user)
 
exten => doorbell,1,Answer()
same => n,RTSP-SIP(rtsp://admin:XXXX@192.168.0.70:554/Streaming/Channels/102,0,Hikvision,5060)
```

Above is wotking 'ok' ...

But i want to have more features... is below possible?
Above is based on confernce, it has some disadvantages offcourse, leys say i dont want to use conference

1) When 6000 calls => 6001, is it possible to inject that RTSP stream as video in the SDP/RTP session? maybe also as early media 183 session, maybe with some customizing with ffmpeg and rtp/sdp ? maybe with modifiyn the dial app.c ? or some easier way ?

2) if above is not possible, and i do need to use conference, can i use the RTSP/h264 video in an early media stage, when i do an originate to 6001 , maybe with customizing the originate.c app ? Changing the SDP/RTP (ffmpeg) and save the rtsp to a file that will be used?

3) Above conference is wotking verry good with my softphone (6001), i tried a few (linphone desktop/zoiper/acrobit) i always see the RTSP video ... BUT, when i use Linphone on android, seems i have a black screen instead of the video ... and actually i want to use Linphone as a client, and seems that one is the one bugging me?? Do you have any idea? is it maybe because a framerate/resolution that you used in your app ? Have you tried linphone (android) too? Any idea where i can look at ? i have tried several options in linphone, like codec / video size / fps ... but no help
Is there something i can try/change in your app/code ?

thnx , much appreciated!!

**Comment by pergolafabio** [comment]
about 3 , i created an issue also here...
Maybe you have an idea now?

https://github.com/BelledonneCommunications/linphone-android/issues/1665

**Comment by pergolafabio** [comment]
this is part of the log in linphone:

```
2022-05-05 08:35:06:302 [org.linphone/mediastreamer] WARNING H26xDecoder: corrupted frame
2022-05-05 08:35:06:302 [org.linphone/liblinphone] WARNING MS_VIDEO_DECODER_DECODING_ERRORS
2022-05-05 08:35:06:334 [org.linphone/mediastreamer] WARNING Incomplete H264 frame (missing marker bit after seq number 23212)
2022-05-05 08:35:06:335 [org.linphone/mediastreamer] WARNING H26xDecoder: corrupted frame
2022-05-05 08:35:06:351 [org.linphone/liblinphone] WARNING MS_VIDEO_DECODER_DECODING_ERRORS
2022-05-05 08:35:06:373 [org.linphone/mediastreamer] WARNING Incomplete H264 frame (missing marker bit after seq number 23214)
```
I see in your .c  file below

```
				 * PORT 17.3 sendFrame->subclass is OLD. app_rtsp.new removed this line.
				 * This is trying to indicate the RTP frame has marker bit set (or not).
				 * I can not find anything, other than perhaps AST_CONTROL_SRCUPDATE
				 * that indicates an RTP frame maker being set and in channel.c 
				 * appears to not used.  Will skip for now.
				 */
			     /*	sendFrame->subclass |= rtp->m; OLD */
```

Maybe somehow related?

**Comment by tommyjlong** [comment]
Yeah the original code had a way of passing along the marker bit setting (I don't recall if Asterisk even made use of it), but newer versions of Asterisk restructured their code so that line of code won't compile anymore.  As the comment says, in my porting to Asterisk 17.3, I couldn't find a way to pass the m-bit to Asterisk, and further I couldn't find any Asterisk code that would use it anyway.  

Also, I'll add a reference to my comment on the Belledonne issue: 
https://github.com/BelledonneCommunications/linphone-android/issues/1665#issuecomment-1119005448

**Comment by pergolafabio** [comment]
Yeah, I saw , thnx for feedback!

I'm going to try asterisk 17, with that marker bit setting, to see if that fixes it...
Do you think that's the reason why I dont see any video on asterisk?

**Comment by tommyjlong** [comment]
It won't compile on Asterisk 17.  That's the version I ported the code to.

**Comment by pergolafabio** [comment]
Ah ,ok, I misread... 
Hmm, so that's the end now? Or anything you can do?

I had my dialplan ready, I was able to setup a confbridge, where I invite the rtsp stream as a first_marked user...

So a 1 to 1 call, where the originator is not sending video, the extension that's being called is actually seeing video... Working great :-)

**Comment by tommyjlong** [comment]
> Hmm, so that's the end now? Or anything you can do?
Sometime later I can take a look at Asterisk 18.x to see if it added any support for marker bit pass-through.

Regarding  your setup:
I commend you on being able to setup a video conference. Nice! :)
But I don't have any suggestions to your questions 1 and 2.

**Comment by pergolafabio** [comment]
Np :-) confbridge is indeed working great

Anything you can do to get it working on linphone clients?

**Comment by tommyjlong** [comment]
> Anything you can do to get it working on linphone clients?

Assuming marker bit is the problem, No, not much I can do unless Asterisk adds a way to support marker bit pass-through

**Comment by pergolafabio** [comment]
Yeah, not sure if marker bit is the issue , I just noticed warnings about it..'
You don't use it anymore, your own project?

**Comment by tommyjlong** [comment]
I still use this project, but I have only used it for audio.   I've never tried it for video. When someone rings the doorbell, I pull up a home assistant lovelace card which has a continuous video feed viewing the doorbell camera.  If I want to talk to the person, then I tap a button on the card which places a webrtc/js-sip call to app_rtsp_sip which establishes a 2-way audio connection between the lovelace card and the doorbell.

**Comment by pergolafabio** [comment]
Yes, that's the same what I do now... But I don't want to be limited to use the HA sip Lovelace card...

I get notification from HA, then I join/call the doorbell, upon incoming call... So it's a 1 to 1 call, but when I answer, I invite the rtsp stream as second user, so I have video on my sip softphone

**Comment by pergolafabio** [comment]
well, if you have the chance to test, pls keep me posted

i'm now trying to setup a v4l2 loopback device, so i can inject the stream with ffmpeg to a /dev/video0 device , so i can setup a console uac, to auto answer :-)

that works on asterisk, but the app is better and easier, no extra stuff needed then

**Comment by pergolafabio** [comment]
Are you able to test/troubleshoot the rtsp issue on your end? Otherwise, I need the loopback solution, but then I need to setup a seperate UAC... That's why I liked your solution the best

**Comment by tommyjlong** [comment]
> Are you able to test/troubleshoot the rtsp issue on your end?

What issue are you referring to?

**Comment by pergolafabio** [comment]
That I don't see the stream on linphone, but visible on other clients

**Comment by pergolafabio** [comment]
Hi @tommyjlong , i have another quesion about this project
Is it possible to manipulate the RTP in asterisk?
Lets say , 8000 is my door intercom, that calls 8001
8000 doesnt have a camera, but when 8000 calls to 8001 , i inject the RTSP stream manually ?

is that possible?

**Comment by tommyjlong** [comment]
Here is what I think you are asking: when 8000 calls 8001 they will establish an audio channel (using Asterisk), and you want Asterisk at the same time to 1) connect to a camera's video using RTSP,  and 2) make a video call to 8001 so that a video channel is created between Asterisk and 8001 and then 3) cross-connect the received RTSP video stream to this video channel.

No, I don't know how this can be done

**Comment by pergolafabio** [comment]
Btw, still struggling with your app and linphone for android, it's the only app that doesn't play the rtsp...

All other softphones I tried work fine, except linphone...
Have you tested linphone before?

**Comment by tommyjlong** [comment]
Sorry, haven't tested linphone.

**Comment by pergolafabio** [comment]
Ok , np..

Just looking for a way that your rtsp user calls me, so I can see the video before pickup...

What I do now, if 8000 calls me, I answer and I start a confbrigde and I invite/originate the rtsp app, to the conference, so I can see the he video
